### ISSUE TITLE
overlay pop can not pass input parameter to the form inside of <main>

### ISSUE THREAD

**Issue by bomarleau** [wet-boew/wet-boew#6769]
Hi, I tried to use overlay centred popup. We have a form inside of the div "main" . The popup section has some input parameters for the form. When user clicks "apply" button, some input will be sent with other parameters of the form to the backend. However, every time when the popup is clicked, the section was moved outside of the main.So the input parameters inside the popup section will not be sent to the form. Since it is difficult for our web app to move the form outside of main, is there any better way of resolve this issue?

Thanks,
Bo

**Comment by LaurentGoderre** [comment]
@bomarleau why are you splitting up the form like that?

**Comment by bomarleau** [comment]
There is no split ups. It is part of the jsp. The form has multiple sections with different input. But when popup was clicked, the section was moved by WET from inside the form to outside of the form. I have resolved the issue by adding the following:

	input = $("<input>").attr("type", "hidden").attr("name","blabla").val("value");
	$("#" + formName).append($(input));

**Comment by bomarleau** [comment]
You can close the ticket.

**Comment by LaurentGoderre** [comment]
I don't understand why you use using an overlay to only display part of the form in an overlay?

**Comment by bomarleau** [comment]
There are two parts of the form. One part is opened as usual. one part is a popup. It has default setting, so the user does not always need to make the changes.

**Comment by thomasgohard** [comment]
@bomarleau if part of the form is rarely going to be used by most users, the [details/summary](http://www.w3.org/TR/html51/semantics.html#the-details-element) elements would be more appropriate than an overlay. It would also solve your problem.

**Comment by LaurentGoderre** [comment]
Why a popup though? Why not hide it and then reveal it in the content area if needed?

**Comment by bomarleau** [comment]
I have implemented this way based on the client's requirement. However, even it will work with the additional Javascript, will we have accessiblity issue? How the screen read JAWS read the popups?

**Comment by LaurentGoderre** [comment]
Lightbox are accessible but you should test in your context.

**Comment by hsrudnicki** [comment]
@bomarleau @thomasgohard : So again, are you ready to make a decision in regards to the solutions and close this issue, also confirm it with @LaurentGoderre

**Comment by AlexFirth** [comment]
I have a similar problem.  You can fix form submission by appending to your form but this does not fix validation.  Lightbox rips the fields out of the form and thus they do not validate.

**Comment by hsrudnicki** [comment]
Due to no further discussion/status updates, made "Going Stale" to close this issue or if otherwise?
Either way, please update this issue's status, thank you

**Comment by hsrudnicki** [comment]
Is this still an issue waiting for your consensus/decision to resolve it? Either way, please update this issue's status, whether this issue can be closed as resolved/fixed or if otherwise, thank you

**Comment by hsrudnicki** [comment]
This can be closed, based on the above. If you think otherwise, please update the status of this again, thank you
