### ISSUE TITLE
Overlay Console Error for standard invocation

### ISSUE THREAD

**Issue by redirectdevnull** [wet-boew/wet-boew#8274]
Uncaught TypeError: Cannot read property 'textContent' of undefined
    at s (wet-boew.js:8993)
    at wet-boew.js:9129
s @ wet-boew.js:8993
(anonymous) @ wet-boew.js:9129

**Comment by nschonni** [comment]
What version of WET and browser are you seeing this in? It sounds like it might be a race condition around the language file loading, but I thought that was fixed in most of the plug-ins now.

**Comment by redirectdevnull** [comment]
WET 4.027

Chrome and Firefox.

Pluggins that are loaded at the time were Datatable plugin and Magnifique plugin.

Otherwise, boilerplate code for WET horseshoe.

**Comment by duboisp** [comment]
@redirectdevnull did your page contain at least one ```<h1>``` element?

Here the line where I think raise the error you seen: https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/overlay.js#L123

It seem to be not about race condition.

**Comment by redirectdevnull** [comment]
@duboisp Looks like you are correct, my site title was using an H2.

Seems to have corrected the issue.

Thanks!

**Comment by nthomassin** [comment]
The project documentation should be updated since the Overlay examples still have the H2 tag.

**Comment by duboisp** [comment]
@nthomassin is it not to use ```h2``` for the overlay dialog, it is about having a ```h1``` on the page that identify the main content.

The content of the ```h1``` is re-used when a user print a page with an opened overlay. https://github.com/wet-boew/wet-boew/blob/master/src/plugins/overlay/_print.scss#L39
